SELECT
  id,
  "AdditionalFeedback",
  "Name",
  "OverallRating",
  "SummaryContentAccuracy",
  "SyllabusFileName",
  "SyllabusSummary",
  "SyllabusURL",
  "ResolutionStatus?"
FROM
  "Feedback_AI_Summarizer";